### ISSUE TITLE
awk: field separator FS is empty on macOS 13

### ISSUE THREAD

**Issue by osopolar** [poolpog/bash-otp#13]
I get following message on macOS 13:

> awk: field separator FS is empty

**Comment by poolpog** [comment]
need more info

**Comment by osopolar** [comment]
See commit 0213325c474f86070db91516c7f1499af301b5ae in linked PR.

That is what awk says on macOS. See also https://stackoverflow.com/a/31135987:

> Note that the standards say that the results are unspecified if an empty string is assigned to FS. Some versions of awk will produce the output you showed above in your example. The version of awk on OS/X issues the warning and output. 

And in https://unix.stackexchange.com/a/417122/173958 I found:

> With Brian Kernighan's awk or the ones based on it like on FreeBSD or OpenBSD, note that while an empty FS or an empty third argument passed to split() causes the string to be split into its individual characters (well, bytes, see below), awk -F '' returns an error (awk -v FS= is OK though).

**Comment by poolpog** [comment]
Fixed in commit f2d95c7c3106bd504ec4807833444792d6149573

This awk command did not work for me on macos; I simplified the whole thing with `cut` instead
